2023-09-15 14:41:09,690 - INFO - Upload endpoint hit
2023-09-15 14:41:09,691 - INFO - Rendering upload template
2023-09-15 14:41:18,264 - INFO - Upload endpoint hit
2023-09-15 14:41:18,264 - INFO - Processing POST request
2023-09-15 14:41:18,267 - INFO - File saved as static/uploads/20230915_125557.heic
2023-09-15 14:41:18,486 - INFO - File resized and compressed: static/uploads/20230915_125557.heic
2023-09-15 14:41:18,487 - INFO - File renamed to static/uploads/20230915144118_375x500.jpg
2023-09-15 14:41:21,759 - INFO - DeepFace analysis successful
2023-09-15 14:41:21,759 - INFO - Extracted attributes: (2, 5, 4)
2023-09-15 14:41:21,759 - INFO - Most similar dog ID: 10
2023-09-15 14:41:21,759 - INFO - Most similar dog data: (2, 5, 4, 'Lobita', 'Fue rescatada con una fractura en su columna. Luego de 6 meses luchando, volvió a caminar. Castrada, cariñosa y amante de estar dentro de casa.')
2023-09-15 14:44:37,446 - INFO - Upload endpoint hit
2023-09-15 14:44:37,446 - INFO - Rendering upload template
2023-09-15 14:44:44,523 - INFO - Upload endpoint hit
2023-09-15 14:44:44,523 - INFO - Processing POST request
2023-09-15 14:44:44,524 - INFO - File saved as static/uploads/20230915174256_500x375.jpg
2023-09-15 14:44:44,526 - INFO - File resized and compressed: static/uploads/20230915174256_500x375.jpg
2023-09-15 14:44:44,526 - INFO - File renamed to static/uploads/20230915144444_500x375.jpg
2023-09-15 14:44:44,555 - ERROR - Error during DeepFace analysis: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
2023-09-15 14:44:44,556 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/victhor/experimentos/perros2/app.py", line 184, in upload
    raise e
  File "/home/victhor/experimentos/perros2/app.py", line 180, in upload
    result = DeepFace.analyze(new_filepath)
  File "/home/victhor/.local/lib/python3.10/site-packages/deepface/DeepFace.py", line 313, in analyze
    img_objs = functions.extract_faces(
  File "/home/victhor/.local/lib/python3.10/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
2023-09-15 14:45:03,831 - INFO - Upload endpoint hit
2023-09-15 14:45:03,831 - INFO - Rendering upload template
2023-09-15 14:45:11,028 - INFO - Upload endpoint hit
2023-09-15 14:45:11,028 - INFO - Processing POST request
2023-09-15 14:45:11,029 - INFO - File saved as static/uploads/20230915174256_500x375.jpg
2023-09-15 14:45:11,030 - INFO - File resized and compressed: static/uploads/20230915174256_500x375.jpg
2023-09-15 14:45:11,030 - INFO - File renamed to static/uploads/20230915144511_500x375.jpg
2023-09-15 14:45:11,044 - ERROR - Error during DeepFace analysis: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
2023-09-15 14:45:11,044 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/victhor/experimentos/perros2/app.py", line 184, in upload
    raise e
  File "/home/victhor/experimentos/perros2/app.py", line 180, in upload
    result = DeepFace.analyze(new_filepath)
  File "/home/victhor/.local/lib/python3.10/site-packages/deepface/DeepFace.py", line 313, in analyze
    img_objs = functions.extract_faces(
  File "/home/victhor/.local/lib/python3.10/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
2023-09-15 14:50:08,128 - INFO - Upload endpoint hit
2023-09-15 14:50:08,128 - INFO - Rendering upload template
2023-09-15 14:50:21,232 - INFO - Upload endpoint hit
2023-09-15 14:50:21,232 - INFO - Processing POST request
2023-09-15 14:50:21,235 - INFO - File saved as static/uploads/20230915_125557.heic
2023-09-15 14:50:21,411 - INFO - File resized and compressed: static/uploads/20230915_125557.heic
2023-09-15 14:50:21,411 - INFO - File renamed to static/uploads/20230915145021_2544x3392.jpg
2023-09-15 14:50:25,280 - INFO - DeepFace analysis successful
2023-09-15 14:50:25,281 - INFO - Extracted attributes: (2, 3, 4)
2023-09-15 14:50:25,281 - INFO - Most similar dog ID: 2
2023-09-15 14:50:25,281 - INFO - Most similar dog data: (2, 2, 5, 'Polo', 'Es adulto jóven y está castrado. 50% fila, 50% gran danés. 100% cariñoso.')
2023-09-15 15:43:19,416 - INFO - Upload endpoint hit
2023-09-15 15:43:19,416 - INFO - Rendering upload template
2023-09-15 15:47:47,561 - INFO - Upload endpoint hit
2023-09-15 15:47:47,561 - INFO - Rendering upload template
2023-09-15 15:49:00,419 - INFO - Upload endpoint hit
2023-09-15 15:49:00,419 - INFO - Rendering upload template
2023-09-15 15:49:08,219 - INFO - Upload endpoint hit
2023-09-15 15:49:08,220 - INFO - Rendering upload template
2023-09-15 15:52:18,908 - INFO - Upload endpoint hit
2023-09-15 15:52:18,908 - INFO - Rendering upload template
2023-09-15 15:53:18,326 - INFO - Upload endpoint hit
2023-09-15 15:53:18,326 - INFO - Rendering upload template
2023-09-15 15:53:57,819 - INFO - Upload endpoint hit
2023-09-15 15:53:57,820 - INFO - Rendering upload template
2023-09-15 15:54:07,803 - INFO - Upload endpoint hit
2023-09-15 15:54:07,803 - INFO - Processing POST request
2023-09-15 15:54:07,807 - INFO - File saved as static/uploads/pexels-cottonbro-studio-5119214.jpg
2023-09-15 15:54:07,809 - ERROR - Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/victhor/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/victhor/experimentos/perros2/app.py", line 184, in upload
    resize_and_compress_image_from_path(filename)
  File "/home/victhor/experimentos/perros2/app.py", line 120, in resize_and_compress_image_from_path
    img = correct_image_rotation(img)
  File "/home/victhor/experimentos/perros2/app.py", line 82, in correct_image_rotation
    if exif[orientation] == 2:
TypeError: 'NoneType' object is not subscriptable
2023-09-15 15:57:24,287 - INFO - Upload endpoint hit
2023-09-15 15:57:24,288 - INFO - Rendering upload template
2023-09-15 15:57:34,124 - INFO - Upload endpoint hit
2023-09-15 15:57:34,124 - INFO - Processing POST request
2023-09-15 15:57:34,126 - INFO - File saved as static/uploads/mauro_base_00000.jpg
2023-09-15 15:57:34,151 - INFO - File resized and compressed: static/uploads/mauro_base_00000.jpg
2023-09-15 15:57:34,151 - INFO - File renamed to static/uploads/20230915155734.jpg
2023-09-15 15:57:37,553 - INFO - Extracted attributes: (2, 4, 5)
2023-09-15 15:57:37,554 - INFO - Most similar dog ID: 19
2023-09-15 15:57:37,554 - INFO - Most similar dog data: (1, 4, 6, 'Aaron', '3 meses. Va a ser un perro grande. Es muy juguetón y mimoso. Le gusta estár a upa.')
2023-09-15 16:14:32,254 - INFO - Upload endpoint hit
2023-09-15 16:14:32,255 - INFO - Rendering upload template
2023-09-15 16:41:02,296 - INFO - Upload endpoint hit
2023-09-15 16:41:02,296 - INFO - Rendering upload template
2023-09-15 16:41:10,458 - INFO - Upload endpoint hit
2023-09-15 16:41:10,458 - INFO - Processing POST request
2023-09-15 16:41:10,462 - INFO - File saved as static/uploads/pexels-cottonbro-studio-5119214.jpg
2023-09-15 16:41:10,682 - INFO - File resized and compressed: static/uploads/pexels-cottonbro-studio-5119214.jpg
2023-09-15 16:41:10,683 - INFO - File renamed to static/uploads/20230915164110.jpg
2023-09-15 16:41:15,237 - INFO - Extracted attributes: (2, 3, 6)
2023-09-15 16:41:15,237 - INFO - Most similar dog ID: 2
2023-09-15 16:41:15,237 - INFO - Most similar dog data: (2, 2, 5, 'Polo', 'Es adulto jóven y está castrado. 50% fila, 50% gran danés. 100% cariñoso.')
2023-09-15 16:42:43,268 - INFO - Upload endpoint hit
2023-09-15 16:42:43,268 - INFO - Processing POST request
2023-09-15 16:42:43,271 - INFO - File saved as static/uploads/pexels-cottonbro-studio-5119214.jpg
2023-09-15 16:42:43,495 - INFO - File resized and compressed: static/uploads/pexels-cottonbro-studio-5119214.jpg
